name: Auto Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"   # 每天0点自动同步，可按需调整
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: SukkaW/Surge
          upstream_sync_branch: master
          target_sync_branch: master
          test_mode: false
